### ISSUE TITLE
API checks

### ISSUE THREAD

**Issue by Ibrahim-Tech-Emplifi** [IbrahimAkbar-tech/cta-troubleshooting#7]
We have a function to check if a client is API or not.

If possible, we should also open the call journey if they are.

Add the piece of code to open the call journey if client is API.

@MSumeer @IbrahimAkbar-tech 

Please ensure you create a new branch for any new implementation or PR will be declined.

**Comment by IbrahimAkbar-tech** [comment]
This was completed as part of branch https://github.com/IbrahimAkbar-tech/cta-troubleshooting/pull/8
